### ISSUE TITLE
How about PS2 port? Really :)

### ISSUE THREAD

**Issue by DartPower** [odamex/odamex#259]
Can you port to PlayStation 2? Like the Xbox version :D

Also check this
https://github.com/cosmito/ps2doom
https://github.com/ps2dev/ps2sdk

Please answer, this is a very easy or bad idea? 
This is is will be cool + also with PS2's DEV9 (Network play)

**Comment by Ch0wW** [comment]
If the PS2 SDK has cURL, SDL1.2 or SDL2.0, libPNG, libz and can support it, it could be looked. But the fact it's too old won't be really beneficial. Besides, I'm totally unaware if there are those libs, how to make it compatible, that kind of stuff, and most importantly, how "active" the PS2 homebrew community is.

If I was able to, I'd have said "OK" for a PS3 port though... Yet it seems it's entirely forgotten, with a huge lack of super common libraries... And yet I'm looking a way to port it to PSVita first.

**Comment by DartPower** [comment]
I think porting idea is good. 

Also i think this is possible to suggest candidates: 
PS2 (in this thread)
PS3 (Idea of @Ch0wW)
PSVita (Also Idea ^ :D)
DOS? (DJGPP?) Oh nvm, this is a my very old dream idea...
GameCube (also as Wii, but IDK this have a need libraries or not)
... and ...
Android ? 

Or... How about libretro in future? (im forgot, im asked or not)

This ideas is good to you? 😃

**Comment by Ch0wW** [comment]
Again, if there aren't the required libraries to the console devkit, porting it will be impossible. That's something you have to remember.

DOS is out of the question, it has been discussed several times in the Discord server.
PS2 is also out of the question: everything is severely outdated, porting it is impossible at the current state. (just checked it)
PS3 is also not possible due to the non-presence of a SDL library for our needs.
PSVita is currently in the works, there are a lot of stuff to modify to make it work.
Gamecube/Wii/WiiU is currently unsupported due to the lack of cURL, required since 0.9.0.
Android, why not, but we need developpers for that. Sadly most of us don't have experience with porting it to Android.

Libretro was thought a while ago, we might support it in the near future. Again, we need devs and time for that.

**Comment by DartPower** [comment]
Thanks a lot for answers! 😃 
Can me rename this thread to "Porting thread" instead the closing issue? :)

**Comment by leximayfield** [comment]
Porting Odamex to retrocomputing targets is a fun hobbyist thing that some of our developers do on the side, but those happen because the developers have a personal desire to see them happen, not because anybody asked us to.  I don't foresee the team "taking requests" for ports.

Personally, the only port I am interested in doing is targeting libretro, in the hopes to facilitate ease of porting to other retro-computing platforms.  However, this is on a very very very back burner, as there are many more pressing things that I think my time would be better spent on.

So yeah, I'm going to close this.  If you want to see Odamex on the PS2, I would recommend reaching out to a developer more familiar with the platform, or try a hand at it yourself.
