### ISSUE TITLE
[BUG] Protobuf Issue Compendium

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#329]
**Describe the bug**
Client crashes, issues, etc encountered during Protobuf branch testing

**Screenshots, NetDemos, & Crash Dumps**
See dumps and information in comments below

**Comment by rakohus** [comment]
Client crash that occurred during Sunlust survival coop. Crash happened after both players in the servers lost all their lives.

[odamex_gfb8b_4860_20210429T043300.zip](https://github.com/odamex/odamex/files/6396344/odamex_gfb8b_4860_20210429T043300.zip)

**Comment by rakohus** [comment]
Crash occurred on Survival Coop - Sunlust map18. Crash happened, nobody died. We're unsure if the crash is related to the comment above.

[odamex_gfb8b_13308_20210429T074505.zip](https://github.com/odamex/odamex/files/6397011/odamex_gfb8b_13308_20210429T074505.zip)

**Comment by rakohus** [comment]
Crash on connect to Super Rocket Arena Turbo server. Wad is RKT_A2. Server can be found on WDL Dev Branch test servers.

[odamex_gfb8b_15840_20210429T074741.zip](https://github.com/odamex/odamex/files/6397023/odamex_gfb8b_15840_20210429T074741.zip)

**Comment by rakohus** [comment]
Dehacked sync issues. Wad is RKT_A2. Can be seen on Super Rocket Arena Turbo server. Starting health should be 5, but it reset to 100. Server seems to not care about the health values. Screenshot is attached where you can see I'm "dead" on the client but shooting a rocket.

![Odamex_DM_20210429_035428](https://user-images.githubusercontent.com/22926877/116518749-a87d1180-a89e-11eb-955e-49666565ef6e.png)

**Comment by rakohus** [comment]
Connect on server crash. Never made it into the map. Sunlust survival coop.

[odamex_gfb8b_18960_20210429T080137.zip](https://github.com/odamex/odamex/files/6397099/odamex_gfb8b_18960_20210429T080137.zip)

**Comment by rakohus** [comment]
Changing teams in TLMS is messed up. If you're in-game alone, and use changeteams ccmd, your team will change on the server BUT your player will not die. Doesn't seem to happen during a live game.

**Comment by rakohus** [comment]
Try to connect to Sunlust Map30. Connection never happens and you're left with a blinking console cursor. This build has the commit with "A faster version of P_TranslateTeleportThings".

**Comment by leximayfield** [comment]
I fixed a major source of crashing due to a null target/tracer pointer deref on update - this is such a common message and common thing to update that I'm surprised it worked at all.  See if your stability is any better after these commits.

Desynced starting health is something I've seen on `stable` as well - might have something to do with my recent DeHackEd updates.  I think @Ch0wW is looking into it.

Sunlust getting stuck on connect is because I forgot to add the "send packet when buffer gets too big" logic.  I re-added the logic, but because we have protobufs, instead of blanketly sending when we go over 600 bytes, I can tell how big the message we're about to write is and send when the next message would go over 1200 bytes, which is a reasonable upper bound on the size of a UDP packet.  Bigger packets == fewer chances for packetloss and mixed-up ordering.

**Comment by rakohus** [comment]
Let's actually not do this all in one giant bug. There are probably better ways to do this. @AlexMax has already fixed the one true protobuf issue here and other issues exist beyond protobuf builds. Closing this.
