### ISSUE TITLE
[BUG] Client Freezes mid-game

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#337]
**Describe the bug**
Client freezes entirely. Affected all clients on the server. Screenshots from multiple players who were able to get a console screenshot.

**Build that the bug occurred in**
0.9 Stable

**To Reproduce**
Unknown how to reliably reproduce.

**Screenshots, NetDemos, & Crash Dumps**
![image](https://user-images.githubusercontent.com/22926877/116774812-11928f80-aa2d-11eb-8744-4841ec21f8f9.png)

![image](https://user-images.githubusercontent.com/22926877/116774820-1bb48e00-aa2d-11eb-8fe8-e2b0664265ac.png)

**Comment by leximayfield** [comment]
This is an instance of Zone heap corruption.  The zone is just a solid block of memory allocated ahead of time, and its use might have made sense in 1993 when allocation was expensive, but there's no real reason for it to be used as of now, and it just opens yourself up for trouble.

Please test `zone-rework`.  That branch basically takes the existing Odamex "Faux Zone" class and gets it the rest of the way into a replacement of the original heap.  Instead of allocating a zone of memory, it merely allocates using `malloc` and simply keeps tagging and ownership bookkeeping in a hashtable.

**Comment by rakohus** [comment]
Haven't seen this occur again. Believe that the Zone heap fixes in PR #344 helped. Closing the bug, will reopen or file new issue if necessary.
