### ISSUE TITLE
[FEATURE] --version command line parameter

### ISSUE THREAD

**Issue by fuzztooth** [odamex/odamex#349]
--version command line parameter, spits out semantic version to stderr/stdout (whichever) and exits.

Could include optional commit/resource revision after as long as there is a separator such as space or +.

**Comment by leximayfield** [comment]
On Linux, this is pretty trivial, no problem.

On Windows it is trivial for `odasrv`, but might be a problem for our other apps because they are compiled as Win32 and don't have access to stdout and don't even block the console on execution.

On Mac I'm not really sure what the correct play is here.  My memory is that `odasrv` is UNIX executable while the others are .app's.

My gut is telling me that on platforms where we don't have access to a stdout the users can see, the best thing we can do is show a dialog box and exit.  I've already got a generic dialog box function that should help us out on Windows and Mac.

**Comment by fuzztooth** [comment]
I appreciate what you're saying, however "seeing" the version isn't really the point.  The point is to obtain the version from the client executable for ingestion by another process or application.

**Comment by leximayfield** [comment]
I've got #526 ready for a looksee.

**Comment by rakohus** [comment]
Introduced in PR #526. Merged to protobreak for inclusion in Odamex 10.0.0 in [6b34e0b](https://github.com/odamex/odamex/commit/6b34e0bcbc209580e9ef8b350820e854636ebcf3).
