### ISSUE TITLE
[BUG] Windows: In Start Menu, "Odamex User Folder" points to wrong location

### ISSUE THREAD

**Issue by Some1NamedNate** [odamex/odamex#360]
As of v0.9.0, when clicking on "Odamex User Folder" in the Start Menu in Windows, it points to `%USERPROFILE%\Documents\My Games\Odamex` instead of `%LOCALAPPDATA%\Programs\odamex` when Odamex is installed for one user.

**Comment by leximayfield** [comment]
If you install Odamex, that is the correct user folder no matter if you install it as a user or globally.  The bug here is that the Odamex 0.9.0 installer did not correctly set up the non-portable behavior, so global installations were completely broken and user installations acted like portable installations with start menu items.

That bug should be taken care of for the 0.9.1 installer.

**Comment by Some1NamedNate** [comment]
Thanks so much for your awareness.
