### ISSUE TITLE
[BUG] v0.9.5 Barrel doesn't explode for Eviternity death exits

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#469]
In the death exits for maps 05 and 10 (and presumably the rest too) of Eviternity, the barrel doesn't explode, stopping the avatar from crossing the exit line

![unknown2](https://user-images.githubusercontent.com/84749759/137232370-0e82b324-4005-458e-8ec6-6da5e91845a6.png)
![unknown](https://user-images.githubusercontent.com/84749759/137232373-1b3d4269-b548-4c4b-ade2-1a26e3dd3425.png)

**Comment by leximayfield** [comment]
For the record, avatars are our voodoo doll system that uses a unique THING instead of trying to give each player a voodoo doll.

At this moment, avatars do not take damage.  However, not only is this avatar not taking damage, it's also not exploding the barrel.  So there is a novel bug here.

**Comment by leximayfield** [comment]
Should be fixed now.  Avatars blow up the barrel and then get forced into the exit.

**Comment by deat322** [comment]
If a voodoo doll is placed overlapping barrels on a map, the barrels immediately explode and the avatar takes damage, killing the player immediately if designed in a way to kill the player.

Example WAD attached
[odaboom.zip](https://github.com/odamex/odamex/files/8029410/odaboom.zip)

**Comment by leximayfield** [comment]
@deat322 Avatars not doing damage to players is not quite the same bug.

Normally I would suggest you open another bug, but I'm not sure that I want to damage players through avatars.  Coop has multiple players and respawning, and even if we could possibly correctly target the ire of voodoo damage - which we can't, since we're client server with 5+ players joining in the middle of the game - there's no guarantee that the voodoo damage is correctly set up to account for respawning players.  I imagine it would either be a one-time annoyance that you can just respawn past or catastrophic if the damage never stopped.

**Comment by rakohus** [comment]
Tested both of these today and confirmed they are fixed. @deat322's request is a separate one and also, one we may not pursue due to the way we handle avatars.
