### ISSUE TITLE
[BUG] PortMIDI is not handling pitch bends too well

### ISSUE THREAD

**Issue by Some1NamedNate** [odamex/odamex#492]
**Describe the bug**
In MAP23 of TWANGO1.WAD, the guitar's bend is more intense than what the MIDI specified.

**Build that the bug occurred in**
0.9.5

**To Reproduce**
With "Music Backend" set to PortMIDI, load TWANGO1.WAD and warp to MAP23.

**Expected behavior**
The pitch bend should be handled correctly.

**Comment by boomlinde** [comment]
The problem here is probably that the MIDI bend range was changed (perhaps in a song playing on another map). Ideally, I think bend range should be reset to +/-2 semitones between song changes. This can be done  with RPN message 0, i.e. by setting RPN address to 0 with CC#100 and CC#101, and then setting the value to two in CC#6.

Other parameters should also be reset. In the best of worlds, all controllers, but I don't know what they all initialize to. But a common problem in Doom ports is that they leave the modulation wheel unchanged between map changes, so sometimes you get crazy vibratos where you shouldn't have them. This should be reset by setting CC#1 to 0.

Various MIDI modules also have reset functions available via SysEx. For SC-55 for example, you can send it the SysEx packet sequence "F0 41 10 42 12 40 00 7F 00 41 F7" (hex encoded) to make it reset all controllers and settings and set up for GM mode. I think allowing users to specify a SysEx sequence to run between each song change would be a great feature. I wonder what Doom does...

**Comment by Some1NamedNate** [comment]
A reset command in between MIDI's (Map -> Intermission -> Map, etc.) would be nice.

**Comment by rakohus** [comment]
Fixed by @ceski-1 patch. Thanks for report @Some1NamedNate
