### ISSUE TITLE
[FEATURE] Typing in console + enter should default to the say command (quake 3 behavior) 

### ISSUE THREAD

**Issue by endless-r0ad** [odamex/odamex#493]
With the console down, typing and pressing enter should default to the chat command 'say'.  

Currently this results in 'unknown command ....'  

This is a user friendly feature, allowing more of the chat backlog to be read while chatting.  

Example -

https://user-images.githubusercontent.com/24723883/146808106-11c5aad4-6ab2-4d93-9d02-ba0202a14022.mp4

**Comment by leximayfield** [comment]
This is not a feature that we are terribly keen on.  It is convenient for chatting, but comes with a few downsides.

- The console window is a suboptimal chat window since that is where obituaries and pickup messages end up as well.
- Inadvertent chatting when you mistype the name of a command.  This can range from benign to catastrophic if RCON passwords are involved.

However, we do understand that it would be nice to have a backlog when chatting.  This is something we plan to eventually address in the standard HUD itself.
