### ISSUE TITLE
[BUG] Death exits in Valiant don't lead to next level

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#682]
**Describe the bug**
When exiting any of the levels that end in a death exit in Valiant, the results screen is shown and then it restarts the level instead of progressing to the next level

**Build that the bug occurred in**
10.1

**Expected behavior**
The next level to start.

**Comment by rakohus** [comment]
I think this may be related to mapinfo changes we did going into 10.X. @DeathEgg any insight?

**Comment by DeathEgg** [comment]
> I think this may be related to mapinfo changes we did going into 10.X. @DeathEgg any insight?

The issue is we currently don't support `endgame` keys for `next` maps- something that Valiant uses for death exits specifically. When I get the time I'll look into if a hot fix is possible, but likely the best course of action is for me to dive into supporting ZDoom's MAPINFO custom intermission screens sooner rather than later.

**Comment by rakohus** [comment]
No longer a problem in the current builds after @bcahue's mapinfo fixes.
