### ISSUE TITLE
[BUG] Horde boss monsters don't trigger (most) linedef specials

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#699]
**Describe the bug**
In Odamex (Doom in Hexen Format), while monsters spawned from other monster spawners appear to walkover trigger a script execute (action 80), end game (action 75), teleport (action 70), and ceiling lower and crush dist (action 97) linedef specials, boss monsters from a horde wave appear to trigger only particular line actions, such as teleport (action 70).

**Build that the bug occurred in**
Odamex v10.1 (G0A84-8300)

**To Reproduce**
If you're quick and use "hordeboss" with the test WAD attached, you'll notice wave boss monsters do not trigger the End Game special. Changing the special in the map to 80 for Script Execute will show a message for normal monsters, but not wave boss monsters. In contrast, you'll notice the Teleport action (70) with a sector tag of 1 will teleport wave boss monsters as well as normal wave monsters

**Expected behavior**
All potential linedef specials with "Monster walks over" trigger to apply to Wave Boss monsters.

**Screenshots, NetDemos, & Crash Dumps**
Attached test wad.

**Additional context**
Didn't test all specials, but listed the ones I did for the sake of the report.
[monster-horde-trigger.zip](https://github.com/odamex/odamex/files/9051729/monster-horde-trigger.zip)

**Comment by bcahue** [comment]
The reason Horde boss monsters don't trigger linedefs is because they add MF2_BOSS as a mobj flag to the boss, which forces each spechit (the functionality required for monsters to cross lindefs) to be listed as a "bossaction" which only supports teleports.

Whether or not we want this functionality, I will leave up to the Odamex team. In my opinion, we should not have this flag, as it was designed to trigger special map lines on death, like Mancubus' in MAP07, etc.
