### ISSUE TITLE
[BUG] Custom colormap/invul range is not used

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#703]
**Describe the bug**
It appears as though Odamex does not parse a pwad's custom COLORMAP or at the very least, its invul range. 

**Build that the bug occurred in**
10.1.0 (G0A84-8300)

**To Reproduce**
The easiest way is to load Eviternity and give yourself Invul (idbeholdv). You will see the normal Doom invul colormap range instead of the custom one defined by the wad's COLORMAP.

**Expected behavior**
A lovely cascade of teals to show up when I am invulnerable in Eviternity. Expected working behavior is reproducible on DSDA-Doom.

**Screenshots, NetDemos, & Crash Dumps**
N/A

**Additional context**
N/A

**Comment by leximayfield** [comment]
Not only does this not appear in Odamex, it also doesn't appear in GZDoom either, software or hardware.  Only port I tried that supports it out of the box is DSDA Doom.

Supporting this in 32-bit color I imagine would be a pain in the ass, because 32-bit rendering knows nothing of standard palette indexes to make such a trick possible.  8-bit might work, but this means that there's a feature that only works in 8-bit.

If I'm being honest, I think the _real_ issue here is that Vanilla's inverted white invulnerability ramp is an eye-sore.  You shouldn't have to play eveternity to not have your eyes cooked in exchange for temporary invunerability.
