### ISSUE TITLE
[BUG] Custom monsters perceive 3d bridge things as solid walls

### ISSUE THREAD

**Issue by Xenaero** [odamex/odamex#795]
**Describe the bug**
Custom defined monsters will not path under bridge things while vanilla monsters will

**Build that the bug occurred in**
10.2 official release

**To Reproduce**
Load up Hordamex and go to MAP38. The best way to reproduce this result is with "**hordewave bullpen**", as it contains Spectres, Pinkies, and custom land monsters to test. You'll find that the custom monsters will not be able to path under the 3d bridge things that separate the inner arena from the outer loop, while Spectres and Pinkies can.

**Expected behavior**
Custom monsters to realize that bridge things do not constitute a solid wall.

**Screenshots, NetDemos, & Crash Dumps**
In the following screenshot, I was able to draw the Spectres out under the bridge, but the Doom64 Spectres could not find a way to my supple flesh.
![Odamex_HORDE_20221023_134144](https://user-images.githubusercontent.com/21268474/197417374-3b1de052-a64f-472b-b24d-7fd3c9f4f8a2.png)

**Additional context**
None.

**Comment by bcahue** [comment]
This is because of MF2_PASSMOBJ not being set to Dehacked monsters.

We do have a provision to migrate some thing flags between Doom formats and Hexen formats, so I can add to the calculation there to add MF2_PASSMOBJ in Hexen format for monsters who have MF_COUNTKILL. This will have the unfortunate side effect of skipping any lost soul clones as they do not have MF_COUNTKILL. So, that's the tradeoff. But the "right" way to do this is to not only support ZDoom's Bit2 BEX extension, but also get MTrop to create a patch to support ZDoom's Bit2 BEX extensions for DecoHack.

**Comment by Xenaero** [comment]
@bcahue I can confirm that as of the above linked PR, newly-minted Dehacked monsters are now no longer scared of the bridge things. Thank you for the rapid response.

![Odamex_HORDE_20221023_181514](https://user-images.githubusercontent.com/21268474/197430000-bfb269ba-b980-4467-bae5-6d5e122f2f47.png)
