### ISSUE TITLE
[BUG] Texture corruption in AUGER;ZENITH

### ISSUE THREAD

**Issue by hjri** [odamex/odamex#933]
**Describe the bug**
Some textures in auger zenith appear corrupted

**Build that the bug occurred in**
10.4.0 (master, g5431-17)

**To Reproduce**
`odamex DBP37_AUGZEN.wad DOOM2.WAD +map map08`

Move a bit forward, corrupted textures will be on the sides of the balcony.

**Expected behavior**
Textures aren't corrupted

**Screenshots, NetDemos, & Crash Dumps**
Odamex:  
![image](https://github.com/odamex/odamex/assets/3514245/f22cbc4e-1ad5-4a89-8a2e-93dc4569de54)

GZDoom:  
![image](https://github.com/odamex/odamex/assets/3514245/8a9e6fb1-6268-4583-b8cd-191efe810412)

Woof:
![image](https://github.com/odamex/odamex/assets/3514245/84c6f9dd-e629-4eff-988b-a1b142af0d67)

**Additional context**
This is not the only texture that looks corrupted, there are some other ones

**Comment by bcahue** [comment]
This specific texture has transparency in it, which should be fine (it is in other ports) but in Odamex that data is not set by anything, and some of the random data may be an endpost, which will cause the coordinates to look "melty" as it does as it resets to the top of the texture. We should probably draw textures that have transparency on 1 sided walls with black instead of transparency to avoid this.

**Comment by Acts19quiz** [comment]
> We should probably draw textures that have transparency on 1 sided walls with black instead of transparency to avoid this.

For what it's worth, that's what ZDoom 2.x (and GZDoom) does.

**Comment by bcahue** [comment]
This is fixed and merged to stable.
